#!/bin/sh
# Install and prepare PowerDNS Authoritative on OPNsense/FreeBSD.
# This script intentionally does not configure site-specific listener IPs,
# ACLs, zones, registrar delegation, or firewall rules.
set -eu

PDNS_USER="${PDNS_USER:-pdns}"
PDNS_GROUP="${PDNS_GROUP:-pdns}"
PDNS_DB="${PDNS_DB:-/var/db/pdns/pdns.sqlite3}"
PDNS_CONF="${PDNS_CONF:-/usr/local/etc/pdns/pdns.conf}"
ENABLE_SERVICE="${ENABLE_SERVICE:-no}"
BACKEND="${BACKEND:-gsqlite3}"

log() { printf '%s\n' "$*"; }
run() { log "+ $*"; "$@"; }

if [ "$(id -u)" != "0" ]; then
  echo "ERROR: run as root" >&2
  exit 1
fi

if ! uname -s | grep -qi 'freebsd'; then
  echo "ERROR: this installer is for OPNsense/FreeBSD" >&2
  exit 1
fi

log "Installing PowerDNS Authoritative with SQLite backend"

if command -v pkg >/dev/null 2>&1; then
  run pkg install -y sqlite3 || {
    echo "ERROR: pkg install failed. On some OPNsense installs, powerdns may need to be built from ports." >&2
    echo "Hint: opnsense-code ports && cd /usr/ports/dns/powerdns && make config install clean" >&2
    exit 1
  }
else
  echo "ERROR: pkg command not found" >&2
  exit 1
fi

run mkdir -p "$(dirname "$PDNS_DB")" /usr/local/etc/pdns
run chown "$PDNS_USER:$PDNS_GROUP" "$(dirname "$PDNS_DB")" || true
run chmod 0750 "$(dirname "$PDNS_DB")" || true

if [ ! -f "$PDNS_DB" ]; then
  log "Creating empty SQLite backend database: $PDNS_DB"
  sqlite3 "$PDNS_DB" <<'SQL'
CREATE TABLE domains (
  id                    INTEGER PRIMARY KEY,
  name                  VARCHAR(255) NOT NULL,
  master                VARCHAR(128) DEFAULT NULL,
  last_check            INTEGER DEFAULT NULL,
  type                  VARCHAR(8) NOT NULL,
  notified_serial       INTEGER DEFAULT NULL,
  account               VARCHAR(40) DEFAULT NULL,
  options               VARCHAR(64000) DEFAULT NULL,
  catalog               VARCHAR(255) DEFAULT NULL
);
CREATE UNIQUE INDEX name_index ON domains(name);
CREATE TABLE records (
  id                    INTEGER PRIMARY KEY,
  domain_id             INTEGER DEFAULT NULL,
  name                  VARCHAR(255) DEFAULT NULL,
  type                  VARCHAR(10) DEFAULT NULL,
  content               VARCHAR(64000) DEFAULT NULL,
  ttl                   INTEGER DEFAULT NULL,
  prio                  INTEGER DEFAULT NULL,
  disabled              BOOLEAN DEFAULT 0,
  ordername             VARCHAR(255),
  auth                  BOOL DEFAULT 1,
  FOREIGN KEY(domain_id) REFERENCES domains(id) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE INDEX rec_name_index ON records(name);
CREATE INDEX nametype_index ON records(name,type);
CREATE INDEX domain_id ON records(domain_id);
CREATE INDEX recordorder ON records(domain_id, ordername);
CREATE TABLE supermasters (
  ip                    VARCHAR(64) NOT NULL,
  nameserver            VARCHAR(255) NOT NULL,
  account               VARCHAR(40) NOT NULL,
  PRIMARY KEY(ip, nameserver)
);
CREATE TABLE comments (
  id                    INTEGER PRIMARY KEY,
  domain_id             INTEGER NOT NULL,
  name                  VARCHAR(255) NOT NULL,
  type                  VARCHAR(10) NOT NULL,
  modified_at           INTEGER NOT NULL,
  account               VARCHAR(40) DEFAULT NULL,
  comment               VARCHAR(64000) NOT NULL,
  FOREIGN KEY(domain_id) REFERENCES domains(id) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE INDEX comments_name_type_idx ON comments(name, type);
CREATE INDEX comments_order_idx ON comments(domain_id, modified_at);
CREATE TABLE domainmetadata (
  id                    INTEGER PRIMARY KEY,
  domain_id             INTEGER NOT NULL,
  kind                  VARCHAR(32),
  content               TEXT,
  FOREIGN KEY(domain_id) REFERENCES domains(id) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE INDEX domainmetadata_idx ON domainmetadata(domain_id, kind);
CREATE TABLE cryptokeys (
  id                    INTEGER PRIMARY KEY,
  domain_id             INTEGER NOT NULL,
  flags                 INTEGER NOT NULL,
  active                BOOL,
  published             BOOL DEFAULT 1,
  content               TEXT,
  FOREIGN KEY(domain_id) REFERENCES domains(id) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE INDEX domainidindex ON cryptokeys(domain_id);
CREATE TABLE tsigkeys (
  id                    INTEGER PRIMARY KEY,
  name                  VARCHAR(255),
  algorithm             VARCHAR(50),
  secret                VARCHAR(255)
);
CREATE UNIQUE INDEX namealgoindex ON tsigkeys(name, algorithm);
SQL
  run chown "$PDNS_USER:$PDNS_GROUP" "$PDNS_DB" || true
  run chmod 0640 "$PDNS_DB" || true
else
  log "SQLite database already exists: $PDNS_DB"
fi

if [ ! -f "$PDNS_CONF" ]; then
  log "Writing generic PowerDNS config: $PDNS_CONF"
  cat >"$PDNS_CONF" <<EOF
# Managed baseline generated by install-powerdns-opnsense.sh
# Site-specific listener addresses, API ACLs, and zones should be configured later.
launch=$BACKEND
gsqlite3-database=$PDNS_DB
local-port=53
setuid=$PDNS_USER
setgid=$PDNS_GROUP
loglevel=4
webserver=yes
webserver-address=127.0.0.1
webserver-port=8081
webserver-allow-from=127.0.0.1,::1
api=yes
api-key=
EOF
  run chmod 0600 "$PDNS_CONF"
else
  log "PowerDNS config already exists, leaving untouched: $PDNS_CONF"
fi

if command -v sysrc >/dev/null 2>&1; then
  run sysrc pdns_enable="$ENABLE_SERVICE" || true
fi

if command -v pdns_server >/dev/null 2>&1; then
  log "PowerDNS version:"
  pdns_server --version || true
  log "Checking PowerDNS config:"
  pdns_server --config-dir=/usr/local/etc/pdns --config=check || true
fi

cat <<EOF

Done.

Next steps:
1. Configure listener interface/IPs in the OPNsense PowerDNS Authoritative plugin.
2. Generate/set a PowerDNS API key.
3. Create or import zones.
4. Add firewall rules for authoritative DNS only when ready.
5. Enable and start the service when configuration has been verified:
   sysrc pdns_enable=yes
   service pdns start
EOF
